//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Threading_Demo_Logs
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int sr { get; set; }
        public Nullable<int> data { get; set; }
        public Nullable<System.TimeSpan> t { get; set; }
    }
}
